sonar.projectKey=khw315_NyaaSi-API-Go
sonar.projectName=NyaaSi-API-Go
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,docs/**,scratch/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
